# Generated by Django 5.2.1 on 2026-03-27 09:13

import achievements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(upload_to=achievements.models.achievement_image_path),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
    ]
