# Generated by Django 5.2.1 on 2026-03-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_remove_achievement_image_add_emoji'),
        ('achievements', '0003_seed_initial_data'),
    ]

    operations = [
    ]
