# Generated by Django 5.2.1 on 2026-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_merge_20260327_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='emoji',
            field=models.CharField(default='🏆', max_length=2),
        ),
    ]
