# Generated by Django 5.2.1 on 2026-03-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('emoji', models.CharField(default='🛡️', max_length=4)),
                ('tagline', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('focus', models.CharField(max_length=120)),
                ('topics', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Guild',
                'verbose_name_plural': 'Guilds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='guilds.guild')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guild_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guild membership',
                'verbose_name_plural': 'Guild memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='guild',
            name='users',
            field=models.ManyToManyField(related_name='guilds', through='guilds.GuildMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
