# Generated by Django 5.2.1 on 2026-03-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isParent',
            new_name='is_parent',
        ),
    ]
