# Generated by Django 5.2.1 on 2026-03-27 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_isparent_profile_is_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('test', 'Тест'), ('theory', 'Теория'), ('practice', 'Практика'), ('game', 'Игра')], max_length=20, verbose_name='Тип результата')),
                ('exp_earned', models.IntegerField(default=0, verbose_name='Заработанный опыт')),
                ('content_id', models.IntegerField(blank=True, null=True, verbose_name='ID контента (урока/теста/игры)')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Оценка/баллы')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат пользователя',
                'verbose_name_plural': 'Результаты пользователей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'result_type'], name='users_userr_user_id_186d06_idx'), models.Index(fields=['created_at'], name='users_userr_created_0a1f99_idx')],
            },
        ),
    ]
