# Generated by Django 5.2.1 on 2026-03-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='score',
        ),
    ]
