# Generated by Django 5.2.1 on 2026-03-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userresult_content_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='key',
            field=models.CharField(default='', max_length=20, verbose_name='Ключ результата'),
        ),
    ]
