# Generated by Django 5.2.1 on 2026-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userresult_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresult',
            name='key',
            field=models.CharField(default='', max_length=100, verbose_name='Ключ результата'),
        ),
    ]
